### ISSUE TITLE
Error when running predict

### ISSUE THREAD

**Issue by abahle** [janclemenslab/deepss#3]
During the predict phase I am getting an error and no segments are showing up in the gui. Below you can see the output. Looks like the main problem is **"ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')"**

INFO:root:Predicting song using DeepSS:
INFO:root:   Running inference on audio.
INFO:root:   Model from C:/Users/Andrew/Desktop/quickstart.res/20210421_161522.
c:\users\andrew\anaconda3\envs\dss\lib\site-packages\tensorflow\python\keras\engine\training.py:2325: UserWarning: `Model.state_updates` will be removed in a future version. This property should not be used in TensorFlow 2.0, as `updates` are applied automatically.
  warnings.warn('`Model.state_updates` will be removed in a future version. '
INFO:root:   found 824 instances of segments '[0 1 2 3 4]'.
Traceback (most recent call last):
  File "c:\users\andrew\anaconda3\envs\dss\lib\site-packages\xarray_behave\gui\app.py", line 1315, in <lambda>
    menuitem.triggered.connect(lambda: callback(qt_keycode))
  File "c:\users\andrew\anaconda3\envs\dss\lib\site-packages\xarray_behave\gui\app.py", line 1859, in deepss_predict
    self.event_times.add_time(name + suffix, onset_seconds, offset_seconds, category='segment')
numpy.core._exceptions.UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U11'), dtype('<U11')) -> dtype('<U11')

**Comment by postpop** [comment]
Hi Andrew,

thanks for raising this issue. It arises when `name` or `suffix` are numpy arrays - I fixed this in the GUI package, [xarray-behave](https://github.com/janclemenslab/xarray-behave). 

Can you update xarray-behave to the new version 0.22.3 (`pip install xarray-behave[gui] --upgrade`) and check that the problem is fixed for you? Thanks!

**Comment by abahle** [comment]
Great thanks for your help that fixed the issue! Thanks again for your work on this great tool!
