### ISSUE TITLE
A question about installing DeepSS

### ISSUE THREAD

**Issue by iouyoo** [janclemenslab/deepss#4]
thanks to your replay. the problem is "FileNotFoundError: Could not find module 'd:\anaconda\envs\dss\lib\site-packages\scipy\.libs\libbanded5x.EHDKC2XVYTQQ5MALRS6XN2CUSS6SRL6P.gfortran-win_amd64.dll"
sorry, I'm new to python, I followed the steps to install it, and Anaconda is the latest version.
is it because of the version of python?Which version should I install?
I don't know what that means "output of `conda list`"
thank you.

**Comment by postpop** [comment]
Thank you for the note. This arises from a version conflict (see here [https://stackoverflow.com/questions/67377972/filenotfounderror-could-not-find-module-when-using-jupyter-notebook]).

Downgrading scipy to version 1.6.2. should fix your problem for now:
` conda install scipy=1.6.2 -c conda-forge --force-reinstall`.

Please let me know if that worked.

I'll update the installation file to avoid this problem in the future.

**Comment by iouyoo** [comment]
It didn't work. but by using the command:" pip install scipy==1.6.3 --user", it worked.
thank you for your help.

**Comment by postpop** [comment]
Glad you got it to work. I'll work on a more general fix...
