### ISSUE TITLE
After fresh installation: "Could not import the GUI."

### ISSUE THREAD

**Issue by stein-e** [janclemenslab/deepss#5]
I ran `conda update conda` and `conda env create -f https://raw.githubusercontent.com/janclemenslab/deepss/master/env/deepss_gui.yml -n dss`

after activating the environment, when running `dss gui`, I get:

2021-06-11 13:14:33.126988: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.10.1
Could not import the GUI.
For instructions on how to install the GUI,
check the docs janclemenslab.org/deepss/install.html.

in the dss environment pyside2 is installed - version 5.15.2

**Comment by stein-e** [comment]
installing a new miniconda3 does not fix it.

**Comment by postpop** [comment]
Fixed by reinstalling PySide2 with `conda install -c conda-forge pyside2`.

See [https://stackoverflow.com/questions/63186438/pyside2-installation-problem-on-ubuntu18-04-python-3-8-3-on-anaconda]().
